---
title: "Project 3"
author: "Annie Kelly and David Peterson"
date: "11/18/2021"
output: html_document
---

## Table of Contents
1. [General Info](#general-info)
2. [Instructions](#installation)
3. [Collaboration](#collaboration)

### General Info
***
Our Project Two downloaded and used the Orange data.frame within R. This data set studies the height of five orange trees over time. There are three columns in the dataset: "tree" describes which tree is being measured, "age" is the age measured in days at the measurement point, and "circumference," which is the circumference of the trunk in millimeters. We created a scatterplot with ggplot2; this compared the circumference of the tree trunks with the age of the five orange trees. The functions take the data from the Orange data set, and compile them under what our specific interests are when we are looking for what oranges have a certain circumference. Also, a for loop was made, which allowed to single out and better study the circumferences 150 millimeters. We made the conditionals to make our plots much easier to understand and dictate what data is represented by it; for example, which numbers are chosen from the data set, and what color they are on the plot itself. 

## Instructions
***
* Used the library function to be able to use one of the standard setf packages within R.
    ** The project used library(ggplot2)
* data("Orange") was opened
                                     
* Created the functions to design to plot the circumference of the circumferences of the data set orange:
      ** plot.circ <- function(cutoff){
          Orange$circumference.above <- ifelse(Orange$circumference > cutoff,                                                   Orange$circumference, NA) 
          data <- cbind(1:5); 
          data1 <- cbind(15:20)
          data2 <- cbind(25:30)

* A for loop was used to repeat the line of code; this loop was:
      ** for (i in 1:nrow(data)) {
            if (i == 1) {
              print("i is 1")
           } else {
              print("i is not 1")
         }
        for (j in 1:nrow(data1)) {
             print(paste("FOR 2: ", j))
        for (k in 1:nrow(data2)) {
            cat(paste("FOR 3: ", k, "\n"))

* A conditional expression was made to determine whether true or false
      ** The conditonal statement used was: 
       ggplot(Orange, aes(age, circumference, color=Tree)) + 
           geom_point(size=4, alpha=0.1) + 
           geom_point(aes(x= age, y = circumference.above, color=Tree), size = 4, alpha =      1, inherit.aes = FALSE) + 
           theme_minimal()
    

## Collaboration
***
Annie Kelly and David Peterson collobarated on this project and did this through a GitHub repository.
